"""empty message

Revision ID: ddae147ef2bf
Revises: ee759b8a6d80
Create Date: 2022-10-23 10:33:33.437187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddae147ef2bf'
down_revision = 'ee759b8a6d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'reviews', ['customer_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='unique')
    # ### end Alembic commands ###
